---

- name: "configuration play." 
  hosts: web
  user: ubuntu
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    - ansible_stdout_callback: yaml

  roles:
    - configure-server