---
- name: Creates directory
  file:
    path: /home/ubuntu/backend
    state: directory

- name: "Copy backend files to EC2 server."
  copy:
    src: /root/project/backend/backend.tar.gz
    dest: /home/ubuntu/backend/backend.tar.gz

- name: "Install package dependencies"
  shell: |
    cd /home/ubuntu/backend
    tar xzvf backend.tar.gz
    
- name: Run the backend app
  become: true
  shell: |
    cd /home/ubuntu/backend 
    pm2 start npm --name backend -- start
    pm2 ls